CREATE TABLE IF NOT EXISTS movies(
    id integer  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    director text NOT NULL,
    distribution text, 
    rating integer 
);  

----INSERT MOVIES DATA --------

INSERT INTO movies (name,director,distribution,rating)
VALUES('Contra el Fuego', 'Alexey Nuzhny','Konstantin Khabenskiy,Ivan Yanlokvskiy,Stasya Miloslavskaya', 7 );

INSERT INTO movies (name,director,distribution,rating)
VALUES('Operacion Vanguardia', 'Stanley Tong','Jackie Chan,Yang Yang,Lun Ai,Miya Muqi,Ruohan Xu,Jackson Lou,Eyad Hourani,Zhengting Zhu.', 8 );

INSERT INTO movies (name,director,distribution,rating)
VALUES('Peter Rabbit: Conejo en fuga', 'Will Gluck','Domhnall Gleeson,Rose Byrne,David Oyelowo,Megan Smart', 9 );

INSERT INTO movies (name,director,distribution,rating)
VALUES('SPACE JAM: UNA NUEVA ERA', 'Malcolm D. Lee','LeBron James, Don Cheable , Ceyair J Wright', 10 );